# 1. Introduction to Machine Learning - Homework

## Set up the environment

In [1]:
import numpy as np
import pandas as pd

In [2]:
import wget

### Question 1: Version of NumPy

In [3]:
print("Q1 Answer --> Version of NumPy: ", np.__version__)

Q1 Answer --> Version of NumPy:  1.23.1


## Getting the Car price dataset.

In [4]:
dataset_url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
filename = wget.download(dataset_url)

 76% [........................................................                  ] 1130496 / 1475504

100% [..........................................................................] 1475504 / 1475504

In [5]:
cars_data_set = pd.read_csv('data.csv')

In [6]:
cars_data = cars_data_set
cars_data.shape

(11914, 16)

### Question 2 : How many records are in the dataset?

In [7]:
print("Q2 Answer -->  Number of Records in Data set are :", cars_data.shape[0] )

Q2 Answer -->  Number of Records in Data set are : 11914


### Question 3 : Who are the most frequent car manufacturers (top-3) according to the dataset?

In [8]:
cars_data['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [9]:
cars_data['Make'].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [10]:
print("Q3 Answer -->  most frequent car manufacturers (top-3):")
for idx in cars_data['Make'].value_counts().head(3).index:
    print(idx, end = ' ')

Q3 Answer -->  most frequent car manufacturers (top-3):
Chevrolet Ford Volkswagen 

### Question 4 : What's the number of unique Audi car models in the dataset?

In [11]:
count = cars_data.loc[cars_data["Make"] == "Audi", "Model"].nunique() 

In [12]:
print("Q4 Answer -->  number of unique Audi car models =", count)

Q4 Answer -->  number of unique Audi car models = 34


#### Question 5 : How many columns in the dataset have missing values?

In [13]:
count = cars_data.isnull().any(axis = 0).sum()

In [14]:
print("Q5 Answer -->  number of columns in the dataset have missing values =", count)

Q5 Answer -->  number of columns in the dataset have missing values = 5


### Question 6
1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

In [15]:
# median value of "Engine Cylinders" column
median1 = cars_data["Engine Cylinders"].median()

In [16]:
#most frequent value of the same "Engine Cylinders".
cars_data["Engine Cylinders"].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [17]:
cars_data["Engine Cylinders"].fillna(cars_data["Engine Cylinders"].mode()[0],inplace = True)

In [18]:
median2 = cars_data["Engine Cylinders"].median()

In [19]:
if(median1 == median2):
    print("Q6 Answer -->  Median changed? : No ")
else:
    print("Q6 Answer -->  Median changed? : Yes ")    

Q6 Answer -->  Median changed? : No 


# Question 7
1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the value of the first element of w?

In [20]:
# 1. Select all the "Lotus" cars from the dataset.
cars_data_temp =  cars_data[cars_data['Make'] == 'Lotus']
cars_data_temp.head(5)

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [21]:
cars_data_temp.shape

(29, 16)

In [22]:
# 2. Select only columns "Engine HP", "Engine Cylinders".
cars_data_temp = cars_data_temp[["Engine HP", "Engine Cylinders"]]
cars_data_temp.head(5)

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [23]:
# 3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
cars_data_temp.drop_duplicates(inplace=True)
cars_data_temp.shape

(9, 2)

In [24]:
# 4. Get the underlying NumPy array. Let's call it X.
X = cars_data_temp.to_numpy()
print(X)

[[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]


In [25]:
XT = X.transpose()
print(XT)

[[189. 218. 217. 350. 400. 276. 345. 257. 240.]
 [  4.   4.   4.   8.   6.   6.   6.   4.   4.]]


In [26]:
#5. Compute matrix-matrix multiplication between the transpose of X and X. 
XTX = XT.dot(X)
print(XTX)

[[7.31684e+05 1.34100e+04]
 [1.34100e+04 2.52000e+02]]


In [27]:
#6. Invert XTX.
XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

[[ 5.53084235e-05 -2.94319825e-03]
 [-2.94319825e-03  1.60588447e-01]]


In [28]:
#7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [29]:
#8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = (XTX_inverse.dot(XT)).dot(y)
print(w)

[  4.59494481 -63.56432501]


In [30]:
print("Q7 Answer -->  value of the first element of w? : " , w[0])    

Q7 Answer -->  value of the first element of w? :  4.594944810094551
